(function(){"use strict";var ORDER=["peek","half","expanded"];function stepSnap(order,from,dir){var i=order.indexOf(from);return order[Math.min(Math.max(i+dir,0),order.length-1)];}
function nearestSnap(order,metrics,h){var best=order[0];var bd=Infinity;for(var i=0;i<order.length;i++){var d=Math.abs(metrics[order[i]]-h);if(d<bd){bd=d;best=order[i];}}
return best;}
function velocity(samples){if(!samples||samples.length<2)return 0;var last=samples[samples.length-1];var recent=samples.filter(function(s){return last.t-s.t<=120;});var a=recent[0]||samples[0];var dt=last.t-a.t;if(dt<=0)return 0;return(a.y-last.y)/dt;}
function computeMetrics(opts){var vh=opts.vh;var visible=typeof opts.visible==="number"?opts.visible:vh;var peekMin=opts.peekMin;return{peek:Math.max(peekMin,Math.round(opts.peek)),half:Math.max(peekMin,Math.round(vh*opts.halfVh)),expanded:Math.max(peekMin,Math.round(visible-opts.topGap))};}
var SCRIM_AT={peek:0,half:0.5,expanded:1};function snapLerp(order,metrics,h,at){if(h<=metrics[order[0]])return at[order[0]];for(var i=1;i<order.length;i++){var lo=order[i-1];var hi=order[i];if(h<=metrics[hi]){var span=metrics[hi]-metrics[lo];var t=span>0?(h-metrics[lo])/span:1;return at[lo]+(at[hi]-at[lo])*t;}}
return at[order[order.length-1]];}
function viewportHeights(){var vh=window.innerHeight||document.documentElement.clientHeight;var vv=window.visualViewport;return{vh:vh,visible:vv?Math.round(vv.height):vh};}
function scrollbarWidth(){var w=window.innerWidth-document.documentElement.clientWidth;return w>0?Math.round(w):0;}
function attachSheetDrag(opts){var panel=opts.panel;var order=opts.order||ORDER;var snapMs=typeof opts.snapMs==="number"?opts.snapMs:240;var minHeight=typeof opts.minHeight==="number"?opts.minHeight:56;var closeRatio=typeof opts.closeRatio==="number"?opts.closeRatio:0.6;var swipeV=typeof opts.swipeV==="number"?opts.swipeV:0.45;var drag=null;var suppressClick=false;var suppressTimer=0;function inDragZone(t){if(!t||!t.closest)return false;if(opts.gripSelector&&t.closest(opts.gripSelector))return true;return!!(opts.headSelector&&t.closest(opts.headSelector)&&!t.closest("button"));}
function onDown(e){if(!opts.isActive()||drag)return;if(e.pointerType==="mouse"&&e.button!==0)return;if(!inDragZone(e.target))return;var rect=panel.getBoundingClientRect();if(opts.onCompactChange)opts.onCompactChange(false);drag={id:e.pointerId,y0:e.clientY,h0:rect.height,h:rect.height,from:opts.getSnap(),moved:false,compact:false,samples:[{y:e.clientY,t:e.timeStamp}]};}
function onMove(e){if(!drag||e.pointerId!==drag.id)return;var dy=drag.y0-e.clientY;if(!drag.moved){if(Math.abs(dy)<4)return;drag.moved=true;panel.classList.add("is-dragging");if(opts.onDragStart)opts.onDragStart();try{panel.setPointerCapture(e.pointerId);}catch(err){}}
e.preventDefault();var m=opts.getMetrics();var h=Math.min(Math.max(drag.h0+dy,minHeight),m.expanded);drag.h=h;panel.style.height=h+"px";panel.style.minHeight=h+"px";if(opts.onDragHeight)opts.onDragHeight(h,m);var compact=opts.isCompact?opts.isCompact(h,m):h<(m.peek+m.half)/2;if(compact!==drag.compact){drag.compact=compact;if(opts.onCompactChange)opts.onCompactChange(compact);}
drag.samples.push({y:e.clientY,t:e.timeStamp});if(drag.samples.length>8)drag.samples.shift();}
function onUp(e){if(!drag||e.pointerId!==drag.id)return;var d=drag;drag=null;try{panel.releasePointerCapture(e.pointerId);}catch(err){}
if(opts.onCompactChange)opts.onCompactChange(false);if(opts.onDragEnd)opts.onDragEnd();if(!d.moved){panel.classList.remove("is-dragging");return;}
var m=opts.getMetrics();var v=velocity(d.samples);suppressClick=true;clearTimeout(suppressTimer);suppressTimer=setTimeout(function(){suppressClick=false;},350);if(d.h<m.peek*closeRatio||(d.from===order[0]&&v<-swipeV)){panel.classList.remove("is-dragging");if(opts.onCompactChange)opts.onCompactChange(true);opts.markSnapping();opts.onClose("drag");setTimeout(opts.clearDragHeight,snapMs+90);return;}
var next=Math.abs(v)>swipeV?stepSnap(order,d.from,v>0?1:-1):nearestSnap(order,m,d.h);opts.setSnap(next,true);}
panel.addEventListener("pointerdown",onDown);panel.addEventListener("pointermove",onMove,{passive:false});panel.addEventListener("pointerup",onUp);panel.addEventListener("pointercancel",onUp);panel.addEventListener("click",function(e){if(!opts.isActive()||suppressClick)return;var btn=e.target.closest("button");var isGrip=!!(opts.gripSelector&&e.target.closest(opts.gripSelector));var isHeadGap=!!(opts.headSelector&&e.target.closest(opts.headSelector))&&!btn;if(!isGrip&&!isHeadGap)return;var cur=opts.getSnap();opts.setSnap(cur===order[order.length-1]?order[order.length-2]:stepSnap(order,cur,1));});return{isDragging:function(){return drag!==null;},isSuppressingClick:function(){return suppressClick;}};}
var panels={};var current=null;function api(name){return panels[name]||null;}
function isOpen(name){var p=api(name);return p!==null&&p.isOpen();}
function close(name,via){var p=api(name);if(p===null||!p.isOpen())return;if(current===name)current=null;p.close(via||"switch");}
function closeAll(via){for(var name in panels){if(Object.prototype.hasOwnProperty.call(panels,name))close(name,via);}}
function claim(name){var target=api(name);if(target===null)return false;for(var other in panels){if(!Object.prototype.hasOwnProperty.call(panels,other))continue;if(other!==name&&panels[other].isOpen())close(other,"switch");}
current=name;if(!target.isOpen())target.open();return true;}
function active(){return current!==null&&isOpen(current)?current:null;}
function register(name,panelApi){panels[name]=panelApi;if(!panelApi.isOpen())return;current=name;}
window.__aipmPanels={ORDER:ORDER,register:register,claim:claim,close:close,closeAll:closeAll,isOpen:isOpen,active:active,get:api,attachSheetDrag:attachSheetDrag,stepSnap:stepSnap,nearestSnap:nearestSnap,snapLerp:snapLerp,SCRIM_AT:SCRIM_AT,velocity:velocity,computeMetrics:computeMetrics,viewportHeights:viewportHeights,scrollbarWidth:scrollbarWidth};})();