name: Check Scripts

on:
  pull_request:
    branches:
      - main
    paths:
      - scripts/**
      - hooks/**
      - .remarkrc
      - package.json
      - yarn.lock
      - .prettierrc
      - tsconfig.json
  workflow_dispatch:

jobs:
  check-node-scripts:
    name: Check Node.js Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: '20.20.2'
      - name: Cache Node.js dependencies
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        id: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-node-dev-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-dev-
      - name: Install Node.js dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - name: Check Prettier Format
        run: yarn scripts:format:check
      - name: Check TypeScript Compile
        run: yarn tsc

  check-python-scripts:
    name: Check Python Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.1.0
        with:
          version: "0.12.5"
      - name: Install Python dependencies
        run: uv sync --group dev
      - name: Check Python Syntax
        run: python -m py_compile hooks/*.py scripts/check-characters.py
      - name: Run All Python Unit Tests
        run: |
          uv run python3 -m unittest
